nome = input('Olá! Como eu posso lhe chamar? ')
r = input('Olá {}, poderia me dizer alguma coisa: '.format(nome))
print('O tipo primitivo do que foi digitado é {}'.format(type))
print('Só tem espaço? {}'.format(r.isspace()))
print('É um número? {}'.format(r.isnumeric()))
print('É alfabético? {}'.format(r.isalpha()))
print('É alfanumérico? {}'.format(r.isalnum()))
print('Está somente em maiúsculas? {}'.format(r.isupper()))
print('Está somente em minúsculas? {}'.format(r.islower()))
print('Está com a primeira letra maiúscula? {}'.format(r.istitle()))
