nome = input("Olá, qual é o seu nome? ")
a = input("Olá, {}, escreva o que desejar: ".format(nome))
print('O tipo primitivo de {} é:{}'.format(a, type(a)))
print('Podemos dizer que {} é um número?'.format(a))
print(a.isnumeric())
print('Podemos dizer que {} é uma palavra?' .format(a))
print(a.isalpha())
print('Podemos dizer que {} tem números e letras?'.format(a))
print(a.isalnum())
